name: "Latent CI"
description: "Run AI-powered tests with Latent"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  api-key:
    description: "Your Latent API key"
    required: true
  project-id:
    description: "Latent project ID"
    required: true
  website-url:
    description: "Optional URL to test against (e.g., staging or preview site)"
    required: false
outputs:
  passed:
    description: "Number of tests that passed"
  failed:
    description: "Number of tests that failed"
  total:
    description: "Total number of tests run"
  execution-time:
    description: "Total execution time in seconds"
runs:
  using: "docker"
  image: "Dockerfile"
